### ISSUE TITLE
STM8?

### ISSUE THREAD

**Issue by spth** [stateos/StateOS#1]
The README states that the OS is for ARM and STM8, but I don't see any STM8 Makefile or STM8-specific code. Will there be STM8 support? If yes, via which compiler(s)?

Philipp

**Comment by rajszym** [comment]
Look at StateOS-STM8SDiscovery repository: https://github.com/stateos/StateOS-STM8SDiscovery

**Comment by spth** [comment]
I see. Will this be merged into the main StateOS repository later? Will compilers other than Cosmic be supported?

Philipp

**Comment by rajszym** [comment]
Merge is not needed. Copy "kernel" folder from the main StateOS repository.
Now only the Cosmic compiler is supported. You can naturally adopt it for another compiler.

**Comment by spth** [comment]
Thanks. I've added StateOS to the STM8 RTOS comparison table at http://www.colecovision.eu/stm8/rtoses.shtml.

I currently don't have the time to attempt a port to SDCC, but I'd be willing to help, especially with SDCC-related questions if someone else attempts it.

Philipp

**Comment by rajszym** [comment]
What about https://github.com/stateos/IntrOS-STM8SDiscovery-SDCC ?

**Comment by spth** [comment]
It compiles for me using

~~~~
make SDCC=/usr/local/bin/sd
~~~~

on Debian GNU/Linux. I noticed and fixed a minor issue, and created a pull request, but did not test the code on an STM8S-Discovery yet.

Philipp

**Comment by spth** [comment]
Also, what is the relationship between StateOS and IntrOS?

Philipp

**Comment by rajszym** [comment]
There is no relationship, but functions have similar syntax.

**Comment by rajszym** [comment]
Philipp, could you look at https://github.com/rajszym/StateOS-STM8SDiscovery-SDCC, please?

**Comment by spth** [comment]
I've had a quick look, but didn't test on hardware yet.

The code seems to run into an SDCC bug:
https://sourceforge.net/p/sdcc/bugs/2641/

in lines 211 and 212 of oskernel.c.

A workaround would be to use explicit casts to void *, i.e. replace .top=MAIN_TOP by .top=(void *)MAIN_TOP and do the same for IDLE_TOP.

With that workaround, it compiles for me.

Philipp

**Comment by spth** [comment]
However, them not being the same is a bit confusing. I see you now avoid such issues by using parentheses in the macros, which is a good idea.

Now what we see here is clearly a bug. Since SDCC 3.6.9 #9993, the error message is a bit more verbose, and it becomes clear that SDCC for some reason assumes one of the pointers to be a near pointer (even though near pointers aren't even implemented in the stm8 backend).

Philipp

**Comment by rajszym** [comment]
Another problem I don't understand. This is about interrupt handlers in _osport.c_.

```
_TIM3_UPD_OVF_BRK_IRQHandler:
	clr	a
	div	x, a
```
and
```
_TIM3_CAP_COM_IRQHandler:
	clr	a
	div	x, a
```

**Comment by spth** [comment]
That division is a workaround for a hardware bug. Details on the bug can be found in section "Unexpected DIV/DIVW instruction result in ISR" in some STM8 errata.
SDCC will omit the workaround if it is sure that there are no divisions in the interrupt handler. But since the interrupt handlers in osport.c call functions from other files, SDCC assumes that there might be divisions.

Philipp

**Comment by rajszym** [comment]
Is there any way to avoid this problem? How to convince the compiler that there are no divisions in the interrupt handler?

**Comment by spth** [comment]
If all functions called from the interrupt handler are defined in the same file as the handler, and before the handler, and the function contains neither divisions nor right shifts, the workround should be omitted.

But considering your interrupt handlers are relatively complex already anyway, the clr a and div x, a only add very little overhead. On the STM8, a divison by 0 takes at most 3 cycles.

Philipp

**Comment by rajszym** [comment]
Ok, I thought that divide by zero causes some kind of HardFault. My mistake.

**Comment by rajszym** [comment]
Philipp, another problem: wrong union initialization.
main.c file:
```
struct S { int a; union { int b; int c; }; };

struct S x = { 1, { 2 } };
struct S y = { 5, { 6 } };

int main( void ) { return y.c; }
```
main.rst file:
```
                                     91 	.area INITIALIZER
      008025                         92 __xinit__x:
      008025 00 01                   93 	.dw #0x0001
      008027 00 02                   94 	.dw #0x0002
      008029 00 00                   95 	.dw #0x0000
      00802B                         96 __xinit__y:
      00802B 00 05                   97 	.dw #0x0005
      00802D 00 06                   98 	.dw #0x0006
      00802F 00 00                   99 	.dw #0x0000
```
As you can see, struct S is 4-bytes length but is initialized by 6 bytes.
Function main returns value 5.

Rajmund

**Comment by spth** [comment]
Thanks. I opened a bug report:
https://sourceforge.net/p/sdcc/bugs/2643/

Philipp

**Comment by rajszym** [comment]
This error applies to unnamed unions.
In this case:
```
struct S { int a; union { int b; int c; } q; };

struct S x = { 1, { 2 } };
struct S y = { 5, { 6 } };

int main( void ) { return y.q.c; }
```
there is no error
```
                                     92 	.area INITIALIZER
      008029                         93 __xinit__x:
      008029 00 01                   94 	.dw #0x0001
      00802B 00 02                   95 	.dw #0x0002
      00802D                         96 __xinit__y:
      00802D 00 05                   97 	.dw #0x0005
      00802F 00 06                   98 	.dw #0x0006
                                     99 	.area CABS (ABS)
```
Rajmund

**Comment by rajszym** [comment]
Ok, it seems that the SDCC port for StateOS is working.
https://github.com/rajszym/StateOS-STM8SDiscovery-SDCC

Philipp, I have some questions about SDCC:
1. Should the system save on the stack some compiler global variables when context switching?
2. Is there any variable for the initial stack pointer?

Rajmund

**Comment by spth** [comment]
1. Currently there are no variables that need saving (all local variables are kept in registers and on the stack). This might change in the future when far (24-bit) pointers are implemented.

2. No.

Philipp
